baseurl = "http://www.advmiguelturra.org/"
title = "ADV Miguelturra"
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
languageCode = "es-ES"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-56289011-1"

# Define the number of posts per page
paginate = 10

[menu]

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.main]]
    name = "Equipos"
	identifier = "teams"
	hasChildren = "yes"
    weight = 20

[[menu.main]]
	name = "Senior Femenino"
	parent = "teams"
    url = "/equipos/senior-femenino/"
	weight = 3

[[menu.main]]
	name = "Senior Masculino Nacional"
	parent = "teams"
    url = "/equipos/senior-masculino-nac/"
	weight = 1

[[menu.main]]
	name = "Senior Masculino Regional"
	parent = "teams"
    url = "/equipos/senior-masculino-reg/"
	weight = 2

[[menu.main]]
	name = "Juvenil Femenino"
	parent = "teams"
    url = "/equipos/juvenil-femenino/"
	weight = 4

# [[menu.main]]
# 	name = "advmiguelturra.org"
# 	parent = "teams"
#     url = "/equipos/juvenil-femenino-b/"
# 	weight = 5

[[menu.main]]
	name = "Juvenil Masculino"
	parent = "teams"
    url = "/equipos/juvenil-masculino/"
	weight = 6

[[menu.main]]
    name = "Clasificaciones"
	identifier = "clasif"
	hasChildren = "yes"
	url = "clasif/"
    weight = 30

# [[menu.main]]
# 	name = "Senior Femenino"
# 	parent = "clasif"
#     url = "clasif/seniorfemenino.html"
# 	weight = 1

# [[menu.main]]
# 	name = "Senior Masculino"
# 	parent = "clasif"
#     url = "clasif/seniormasculino.html"
# 	weight = 2

# [[menu.main]]
# 	name = "Juvenil Femenino"
# 	parent = "clasif"
#     url = "clasif/juvenilfemenino.html"
# 	weight = 3

# [[menu.main]]
# 	name = "JF - Eliminatorias"
# 	parent = "clasif"
#     url = "clasif/juvenilfemenino-play-offs.html"
# 	weight = 4

# [[menu.main]]
# 	name = "Juvenil Masculino"
# 	parent = "clasif"
#     url = "clasif/juvenilmasculino.html"
# 	weight = 5

# [[menu.main]]
# 	name = "Liga Regional Cadete Femenina"
# 	parent = "clasif"
#     url = "clasif/regionalcadetefemeninohtml"
# 	weight = 6

# [[menu.main]]
# 	name = "LRCF - Eliminatoria"
# 	parent = "clasif"
#     url = "clasif/rcfemenino-play-off.html"
# 	weight = 7

# [[menu.main]]
# 	name = "Liga Regional Infantil Femenina"
# 	parent = "clasif"
#     url = "clasif/regionalinfantilfemenino.html"
# 	weight = 8

[[menu.main]]
    name = "Fotos"
    url = "https://www.flickr.com/photos/advmiguelturra/albums/"
    weight = 40

[[menu.main]]
    name = "Voley Playa"
    url = "/vplaya/"
    weight = 50

[[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 60

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Flickr"
    url = "https://www.flickr.com/photos/advmiguelturra/albums"
    pre = "<i class='fa fa-2x fa-flickr'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/ADVMiguelturra"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/advmiguelturra"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "YouTube"
    url = "https://www.youtube.com/user/advmiguelturratv"
    pre = "<i class='fa fa-2x fa-youtube'></i>"

#[[menu.topbar]]
#    weight = 4
#    name = "Email"
#    url = "mailto:your@email.com"
#    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    author = "Joaquín"
    defaultKeywords = ["miguelturra", "voley", "voleibol"]
    defaultDescription = "Blog de la Asociación Deportiva de Voleibol de Miguelturra"
    viewMorePostLink = "/blog/"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
	#email = "direccion@advmiguelturra.org"

    about_us = "<p>Somos un club deportivo con sede en Miguelturra. Nuestra pasión es el voleibol y lo practicamos y fomentamos tanto en pista como en playa y de cualquier otra forma que se nos ocurra.</p>"
    copyright = "Copyright (c) 2017, ADV Miguelturra; todos los derechos reservados."

    # Format dates with Go's time formatting
    date_format = "02 01 2006"

    logo = "img/logo.png"
    address = """<p><strong>Pabellón Municipal de Miguelturra</strong>
        <br>Calle de la Juventud, s/n
        <br>13170 Miguelturra
        <br>Ciudad Real
      </p>
      """
    latitude = "38.957849"
    longitude = "-3.886916"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true

[params.features]
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    enable = false

[params.teams]
    # describe in 'data/teams/*yml'
    enable = true
	title = "Equipos"
	subtitle = ""

[params.testimonials]
    # describe in 'data/testimonials/*yml'
    enable = true
    title = "Nosotros"
    subtitle = "Son muchas las personas involucradas en la gestión de la ADV, y que dedican su tiempo y esfuerzo para sacar las cosas adelante. Entrenadores, monitores de EEDD y ayudantes forman parte esencial del trabajo diario del Club. A nivel institucional, la ADV está representada por la Junta Directiva. Éstos son sus principales miembros:"

[params.staff]
    enable = true
    title = "Entrenadores Federados"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "fa fa-newspaper-o"
    title = "¿Quieres saber más?"
    subtitle = "Historia del club, actividades que realizamos y componentes de la junta directiva"
    link_url = "el-club/"
    link_text = "El Club"

[params.ranking]
    enable = true
    icon = "fa fa-trophy"
    title = "Clasificaciones"
    subtitle = "Consulta la clasificación de nuestros equipos en la liga regular federada"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Enlaces"
	subtitle = "Instituciones y organizaciones relacionadas con nosotros y con el voleibol"

[params.sponsors]
    enable = true
    title = "Agradecimientos"
 	subtitle = "Estas son algunas de las empresas que nos patrocinan durante la liga o colaboran con nosotros de manera especial en la organización de nuestras actividades"

[params.recent_posts]
    enable = true
    title = "Publicaciones recientes"
    subtitle = "Últimas entradas y noticias en nuestro blog"
