baseURL = "http://www.advmiguelturra.org/vplaya/"
title = "ADV :: Voley-Playa"
theme = "advbeach"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
languageCode = "es-ES"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-56289011-1"

[params]
    # Format dates with Go's time formatting
    date_format = "02 January 2006"

[menu]

[[menu.main]]
    name = "Cto. Provincial"
    url = "/provincial/"
    weight = 1

[[menu.main]]
    name = "Cto. Regional"
    url = "/regional/"
    weight = 10

[[menu.main]]
    name = "Cto. Nacional"
	identifier = "/nacional/"
	# hasChildren = "yes"
    weight = 20

[[menu.main]]
	name = "Clinic"
	identifier = "/clinic/"
	weight = 30

[[menu.main]]
	name = "Torneo"
	identifier = "/torneo/"
	weight = 40
